### PR TITLE
Remove/update calls to retired method names (closes #87, closes #78)

### LINKED ISSUE #78: A member leaving the Telegram group causes unhandled promise rejection
### Summary
When a member of a Telegram group leaves the group teleirc tries to evaluate https://github.com/RITlug/teleirc/blob/e81ff0bdb23de46559ba985c02aa5677d3b36bd0/lib/TeleIrc.js#L333 resulting in the following trace being thrown:
```
Unhandled rejection ReferenceError: teleirc is not defined
    at TeleIrc.handleTelegramMsg (/home/icflournoy/dev/RITlug/teleirc/lib/TeleIrc.js:335:44)
    at TelegramBot.emit (/home/icflournoy/dev/RITlug/teleirc/node_modules/eventemitter3/index.js:116:35)
    at TelegramBot.processUpdate (/home/icflournoy/dev/RITlug/teleirc/node_modules/node-telegram-bot-api/lib/telegram.js:120:14)
    at /home/icflournoy/dev/RITlug/teleirc/node_modules/node-telegram-bot-api/lib/telegramPolling.js:59:17
    at Array.forEach (native)
    at /home/icflournoy/dev/RITlug/teleirc/node_modules/node-telegram-bot-api/lib/telegramPolling.js:56:17
    at tryCatcher (/home/icflournoy/dev/RITlug/teleirc/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/icflournoy/dev/RITlug/teleirc/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/icflournoy/dev/RITlug/teleirc/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/icflournoy/dev/RITlug/teleirc/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/icflournoy/dev/RITlug/teleirc/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/icflournoy/dev/RITlug/teleirc/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/icflournoy/dev/RITlug/teleirc/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
I have tested using both the default configuration and a custom configuration.
**default**
```
SHOW_ACTION_MESSAGE=true
SHOW_JOIN_MESSAGE=false
SHOW_KICK_MESSAGE=true
SHOW_LEAVE_MESSAGE=false
```

**all-enabled**
```
SHOW_ACTION_MESSAGE=true
SHOW_JOIN_MESSAGE=true
SHOW_KICK_MESSAGE=true
SHOW_LEAVE_MESSAGE=true
```

It's an easy fix I can open a PR for.

### LINKED ISSUE #87: Fix undefined var: "ReferenceError: imgur is not defined"
This is a bug where the existing code in master branch does not work because of an undefined variable:

```
$ docker run --rm -it teleirc-fedora-tmp
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:653:30
Reading config file to get bot API token...
/opt/teleirc/lib/TeleIrc.js:39
      imgur.setClientId(this.config.imgur.imgurClientId);
      ^

ReferenceError: imgur is not defined
    at new TeleIrc (/opt/teleirc/lib/TeleIrc.js:39:7)
    at Object.<anonymous> (/opt/teleirc/teleirc.js:12:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

### PR DESCRIPTION
**Pull request by jwflory**
After #80, a few unused method calls were lying around. For the ones where a clear rename existed, I updated the method name. For the one part where I could not, I removed it.

I manually validated that the bot successfully started and ran. I also [verified](https://i.imgur.com/EShsvZf.jpg) Imgur image upload is working.

### CODE REVIEW

**Comment by jwflory** [comment]
Also, I'm a little intrigued how something like this was overlooked by Travis in the CI run. Might be a separate issue to dig into.

File: lib/TeleIrc.js [hunk 1]
```diff
@@ -35,10 +35,6 @@ class TeleIrc {
       this.errorCodes = new TeleIrcErrorCodes();
     }
 
-    if (this.config.imgur.useImgurForImageLinks) {
-      imgur.setClientId(this.config.imgur.imgurClientId);
```
Comment (thenaterhood) [inline lib/TeleIrc.js]: As far as I know, this call is still needed, it should probably happen in a constructor ....elsewhere.

File: lib/TeleIrc.js [hunk 2]
```diff
@@ -395,7 +391,7 @@ class TeleIrc {
     }
     this.tgEventListener.addListener(
       'photo',
-      this.tgPhotoHandler.ReportPhoto.bind(this.tgPhotoHandler)
+      this.tgPhotoHandler.RelayPhotoMessage.bind(this.tgPhotoHandler)
```
Comment (thenaterhood) [inline lib/TeleIrc.js]: Ah, the dangers of large code reviews - missing simple things like this

File: lib/TeleIrc.js (hunk 1 above)
Comment (jwflory) [reply lib/TeleIrc.js]: @thenaterhood Any suggestions here? I tested the bot fully and it seemed to work without this code, but I couldn't figure out where it belongs. The problem is that the `setClientId()` method is not used anywhere else in the entire project that I could find. This is why I assumed it was legacy code.

Comment (xforever1313) [reply lib/TeleIrc.js]: If I recall correctly, imgur was a global in Teleirc.js.  It was at the top of the file, and it looked like:

```js
let imgur = require("imgur");
```

However, I must have missed this during the massive refactor.  Right now, the require("imgur") is no longer a global (why create it if the user is not using imgur?).  It is passed into the Imgur Telegram Handler's constructor:

```js
    constructor(imgur, enabled, tgbot, action) {
        super(enabled, tgbot, action);
        this._imgur = imgur;
}
```

Which is invoked in initStage5_initTelegramMessageSending in Teleirc.js:

```js
    if (this.config.imgur.useImgurForImageLinks) {
      this.tgPhotoHandler = new TgImgurPhotoHandler(
        require('imgur'),
        true,
        this.tgbot,
        this.sendMessageToIrc.bind(this)
      );
}
```

I'm not entirely sure what setClientId does, since the library's documentation is non-existent.  It _could_ be like an API key???  Whether or not its required for imgur to work, I'm not sure.

If we *do* need it, we might want to consider adding an additional parameter to TgImgurPhotoHandler that takes in the config's imgur class, and calling setClientId inside of it...  Something like:

```js
    constructor(imgur, imgurConfig, enabled, tgbot, action) {
        super(enabled, tgbot, action);
        this._imgur = imgur;
        this._imgur.setClientId(imgurConfig.imgurClientId);
}
```

Note: The mock imgur class in the unit tests will need an empty setClientId function as well.

Comment (xforever1313) [reply lib/TeleIrc.js]: Just curious, @jwflory, is there a file in ~/.imgur whose contents look like a client ID?  That might explain why its still working... it could be loading it to disk.

Comment (xforever1313) [reply lib/TeleIrc.js]: Actually, nevermind, I looked at imgur's source code, and saw this:

```js
// The following client ID is tied to the
// registered 'node-imgur' app and is available
// here for public, anonymous usage via this node
// module only.
var IMGUR_CLIENT_ID = process.env.IMGUR_CLIENT_ID || 'f0ea04148a54268';
```

It looks like if a client ID is not specified, it uses some default one.  We probably don't want that.

File: lib/TeleIrc.js (hunk 2 above)
Comment (xforever1313) [reply lib/TeleIrc.js]: :+1:

File: lib/TeleIrc.js (hunk 1 above)
Comment (jwflory) [reply lib/TeleIrc.js]: @xforever1313 I didn't see a written `imgur.` file in a running instance with the current `HEAD` of the `master` branch.

Comment (jwflory) [reply lib/TeleIrc.js]: @xforever1313 I see. So we need to set the API token as an environment variable? I assume my success with using Imgur in testing was with the default API key then?

Comment (Tjzabel) [reply lib/TeleIrc.js]: @jwflory yep, if you've done this in testing, you would have used the default client id.

In order to upload to imgur, you'll want to send an HTML message. With JS, you'll want to send a JSON POST request.

[Here](https://git.xfce.org/apps/xfce4-screenshooter/tree/lib/screenshooter-imgur.c#n104) is the implementation in C.

[Here](https://ctrlq.org/code/20526-javascript-image-uploader) is information on how to achieve this in JS. 

The general format is looking for an *Authorization* field and appending the Client-ID + API key.

Comment (jwflory) [reply lib/TeleIrc.js]: @Tjzabel @xforever1313 The code for this seems to be here:

https://github.com/RITlug/teleirc/blob/master/lib/TelegramHandlers/TgImgurPhotoHandler.js#L25-L37

But I can't take a guess of how to do this. I don't understand where the Imgur API URL is being formed or how this handler knows what the URL is.

Comment (Tjzabel) [reply lib/TeleIrc.js]: @jwflory @xforever1313 From the code snippet linked, it seems `_UploadImage` is a function override, and `uploadUrl` is the function that does the actual image uploading to Imgur. I can't find any implementation of this function, except in the test cases. 

In the constructor [here](https://github.com/RITlug/teleirc/blob/master/lib/TelegramHandlers/TgImgurPhotoHandler.js#L13), there is an `imgur` object, but I don't know what its purpose is.

It seems we need to create the `uploadUrl` function to handle the actual uploading process within the `TgImgurPhotoHandler.js` file.

**Comment by jwflory** [comment]
@xforever1313 @Tjzabel @thenaterhood @robbyoconnor Do we want to merge this one for now and then focus in on solving #93?

File: lib/TeleIrc.js (hunk 1 above)
Comment (Tjzabel) [reply lib/TeleIrc.js]: Moved comment thread over to issue #93
